# Site settings
author: Jeremy Wood
title: Not yet a coder
header-img: img/home-bg.png
email: js.wood206@gmail.com
copyright_name: Jeremy Wood
description: > # this means to ignore newlines until "baseurl:"
  But I'm working on it
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  J5Wood

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
